# This is a basic workflow to help you get started with Actions

name: Build and Deploy React App via FTP

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ ci-cd ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-and-deploy"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run react build script
      uses: actions/setup-node@v2
      with:
        node-version: '16.13.1'
    - name: Install dependencies
      run: npm ci

    - name: Run the tests
      run: npm test

    - name: Build
      run: npm run build --if-present
      env:
        CI: false

    - name: Deploy
      uses: wangyucode/sftp-upload-action@v1.1
      with:
        host: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: ${{ secrets.FTP_PORT }}
        localDir: 'build'
        remoteDir: '/home/laddkczp/store.laddatop.com'          
